import "./globals.css";
import type { Metadata } from "next";
import Banner from "@/components/Banner";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Blog Onlyblock",
  description: "Generated by Samuel Lajara",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="max-w-7xl mx-auto">
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );
}
